const TICKERS_DATA = {
    "⭐ Highlights": [
        { symbol: "SPY", name: "S&P 500 ETF" },
        { symbol: "QQQ", name: "Nasdaq 100 ETF" },
        { symbol: "NVDA", name: "NVIDIA" },
        { symbol: "TSLA", name: "Tesla" },
        { symbol: "AAPL", name: "Apple" },
        { symbol: "MSFT", name: "Microsoft" },
        { symbol: "BTC-USD", name: "Bitcoin" },
        { symbol: "GC=F", name: "Gold" }
    ],
    "🏛️ US Mega Cap": [
        { symbol: "AAPL", name: "Apple" },
        { symbol: "MSFT", name: "Microsoft" },
        { symbol: "GOOGL", name: "Alphabet A" },
        { symbol: "GOOG", name: "Alphabet C" },
        { symbol: "AMZN", name: "Amazon" },
        { symbol: "NVDA", name: "NVIDIA" },
        { symbol: "META", name: "Meta" },
        { symbol: "TSLA", name: "Tesla" },
        { symbol: "BRK-B", name: "Berkshire B" },
        { symbol: "UNH", name: "UnitedHealth" },
        { symbol: "XOM", name: "Exxon Mobil" },
        { symbol: "JNJ", name: "Johnson & Johnson" },
        { symbol: "V", name: "Visa" },
        { symbol: "JPM", name: "JPMorgan Chase" },
        { symbol: "WMT", name: "Walmart" },
        { symbol: "PG", name: "Procter & Gamble" },
        { symbol: "MA", name: "Mastercard" },
        { symbol: "HD", name: "Home Depot" },
        { symbol: "CVX", name: "Chevron" },
        { symbol: "LLY", name: "Eli Lilly" }
    ],
    "💻 US Tech": [
        { symbol: "AVGO", name: "Broadcom" },
        { symbol: "ORCL", name: "Oracle" },
        { symbol: "ADBE", name: "Adobe" },
        { symbol: "CRM", name: "Salesforce" },
        { symbol: "AMD", name: "AMD" },
        { symbol: "CSCO", name: "Cisco" },
        { symbol: "ACN", name: "Accenture" },
        { symbol: "INTC", name: "Intel" },
        { symbol: "IBM", name: "IBM" },
        { symbol: "QCOM", name: "Qualcomm" },
        { symbol: "TXN", name: "Texas Instruments" },
        { symbol: "INTU", name: "Intuit" },
        { symbol: "AMAT", name: "Applied Materials" },
        { symbol: "NOW", name: "ServiceNow" },
        { symbol: "MU", name: "Micron" },
        { symbol: "LRCX", name: "Lam Research" },
        { symbol: "PANW", name: "Palo Alto Networks" },
        { symbol: "KLAC", name: "KLA Corp" },
        { symbol: "SNPS", name: "Synopsys" },
        { symbol: "CDNS", name: "Cadence" },
        { symbol: "PLTR", name: "Palantir" },
        { symbol: "NET", name: "Cloudflare" },
        { symbol: "CRWD", name: "CrowdStrike" },
        { symbol: "SNOW", name: "Snowflake" },
        { symbol: "DDOG", name: "Datadog" },
        { symbol: "ZS", name: "Zscaler" },
        { symbol: "MRVL", name: "Marvell" },
        { symbol: "FTNT", name: "Fortinet" },
        { symbol: "TEAM", name: "Atlassian" },
        { symbol: "WDAY", name: "Workday" }
    ],
    "🏦 US Finance": [
        { symbol: "BAC", name: "Bank of America" },
        { symbol: "WFC", name: "Wells Fargo" },
        { symbol: "GS", name: "Goldman Sachs" },
        { symbol: "MS", name: "Morgan Stanley" },
        { symbol: "BLK", name: "BlackRock" },
        { symbol: "SCHW", name: "Charles Schwab" },
        { symbol: "C", name: "Citigroup" },
        { symbol: "AXP", name: "American Express" },
        { symbol: "SPGI", name: "S&P Global" },
        { symbol: "CME", name: "CME Group" },
        { symbol: "ICE", name: "ICE" },
        { symbol: "CB", name: "Chubb" },
        { symbol: "PNC", name: "PNC Financial" },
        { symbol: "USB", name: "US Bancorp" },
        { symbol: "TFC", name: "Truist" },
        { symbol: "AON", name: "Aon" },
        { symbol: "MMC", name: "Marsh McLennan" },
        { symbol: "MCO", name: "Moody's" },
        { symbol: "MET", name: "MetLife" },
        { symbol: "AIG", name: "AIG" }
    ],
    "🏥 US Healthcare": [
        { symbol: "ABBV", name: "AbbVie" },
        { symbol: "MRK", name: "Merck" },
        { symbol: "PFE", name: "Pfizer" },
        { symbol: "TMO", name: "Thermo Fisher" },
        { symbol: "ABT", name: "Abbott Labs" },
        { symbol: "DHR", name: "Danaher" },
        { symbol: "BMY", name: "Bristol-Myers" },
        { symbol: "AMGN", name: "Amgen" },
        { symbol: "ISRG", name: "Intuitive Surgical" },
        { symbol: "GILD", name: "Gilead" },
        { symbol: "SYK", name: "Stryker" },
        { symbol: "MDT", name: "Medtronic" },
        { symbol: "CVS", name: "CVS Health" },
        { symbol: "ELV", name: "Elevance Health" },
        { symbol: "CI", name: "Cigna" },
        { symbol: "REGN", name: "Regeneron" },
        { symbol: "VRTX", name: "Vertex" },
        { symbol: "ZTS", name: "Zoetis" },
        { symbol: "BSX", name: "Boston Scientific" },
        { symbol: "BDX", name: "Becton Dickinson" },
        { symbol: "HUM", name: "Humana" },
        { symbol: "MCK", name: "McKesson" },
        { symbol: "EW", name: "Edwards Lifesciences" },
        { symbol: "BIIB", name: "Biogen" },
        { symbol: "MRNA", name: "Moderna" }
    ],
    "🏭 US Industrials": [
        { symbol: "CAT", name: "Caterpillar" },
        { symbol: "RTX", name: "RTX Corp" },
        { symbol: "HON", name: "Honeywell" },
        { symbol: "UNP", name: "Union Pacific" },
        { symbol: "DE", name: "Deere" },
        { symbol: "BA", name: "Boeing" },
        { symbol: "LMT", name: "Lockheed Martin" },
        { symbol: "GE", name: "GE Aerospace" },
        { symbol: "UPS", name: "UPS" },
        { symbol: "ADP", name: "ADP" },
        { symbol: "MMM", name: "3M" },
        { symbol: "ETN", name: "Eaton" },
        { symbol: "ITW", name: "Illinois Tool Works" },
        { symbol: "EMR", name: "Emerson Electric" },
        { symbol: "NOC", name: "Northrop Grumman" },
        { symbol: "GD", name: "General Dynamics" },
        { symbol: "WM", name: "Waste Management" },
        { symbol: "CSX", name: "CSX" },
        { symbol: "NSC", name: "Norfolk Southern" },
        { symbol: "FDX", name: "FedEx" },
        { symbol: "PH", name: "Parker Hannifin" },
        { symbol: "PCAR", name: "PACCAR" },
        { symbol: "TT", name: "Trane Technologies" },
        { symbol: "CTAS", name: "Cintas" },
        { symbol: "ROK", name: "Rockwell Automation" }
    ],
    "🛒 US Consumer": [
        { symbol: "KO", name: "Coca-Cola" },
        { symbol: "PEP", name: "PepsiCo" },
        { symbol: "COST", name: "Costco" },
        { symbol: "MCD", name: "McDonald's" },
        { symbol: "NKE", name: "Nike" },
        { symbol: "DIS", name: "Disney" },
        { symbol: "NFLX", name: "Netflix" },
        { symbol: "SBUX", name: "Starbucks" },
        { symbol: "TGT", name: "Target" },
        { symbol: "LOW", name: "Lowe's" },
        { symbol: "TJX", name: "TJX Companies" },
        { symbol: "EL", name: "Estée Lauder" },
        { symbol: "CL", name: "Colgate-Palmolive" },
        { symbol: "PM", name: "Philip Morris" },
        { symbol: "MO", name: "Altria" },
        { symbol: "MDLZ", name: "Mondelez" },
        { symbol: "KHC", name: "Kraft Heinz" },
        { symbol: "GIS", name: "General Mills" },
        { symbol: "K", name: "Kellogg" },
        { symbol: "HSY", name: "Hershey" },
        { symbol: "CMG", name: "Chipotle" },
        { symbol: "YUM", name: "Yum! Brands" },
        { symbol: "ORLY", name: "O'Reilly Automotive" },
        { symbol: "AZO", name: "AutoZone" },
        { symbol: "ROST", name: "Ross Stores" }
    ],
    "⚡ US Energy": [
        { symbol: "COP", name: "ConocoPhillips" },
        { symbol: "SLB", name: "Schlumberger" },
        { symbol: "EOG", name: "EOG Resources" },
        { symbol: "PSX", name: "Phillips 66" },
        { symbol: "MPC", name: "Marathon Petroleum" },
        { symbol: "VLO", name: "Valero" },
        { symbol: "OXY", name: "Occidental" },
        { symbol: "PXD", name: "Pioneer Natural" },
        { symbol: "DVN", name: "Devon Energy" },
        { symbol: "HAL", name: "Halliburton" },
        { symbol: "WMB", name: "Williams Companies" },
        { symbol: "KMI", name: "Kinder Morgan" },
        { symbol: "OKE", name: "ONEOK" },
        { symbol: "FANG", name: "Diamondback Energy" },
        { symbol: "HES", name: "Hess Corp" }
    ],
    "📡 US Telecom & Utilities": [
        { symbol: "T", name: "AT&T" },
        { symbol: "VZ", name: "Verizon" },
        { symbol: "TMUS", name: "T-Mobile" },
        { symbol: "NEE", name: "NextEra Energy" },
        { symbol: "DUK", name: "Duke Energy" },
        { symbol: "SO", name: "Southern Company" },
        { symbol: "D", name: "Dominion Energy" },
        { symbol: "AEP", name: "American Electric" },
        { symbol: "EXC", name: "Exelon" },
        { symbol: "XEL", name: "Xcel Energy" },
        { symbol: "SRE", name: "Sempra" },
        { symbol: "ED", name: "Con Edison" },
        { symbol: "WEC", name: "WEC Energy" },
        { symbol: "ES", name: "Eversource" },
        { symbol: "AWK", name: "American Water" }
    ],
    "🏠 US Real Estate": [
        { symbol: "PLD", name: "Prologis" },
        { symbol: "AMT", name: "American Tower" },
        { symbol: "EQIX", name: "Equinix" },
        { symbol: "CCI", name: "Crown Castle" },
        { symbol: "PSA", name: "Public Storage" },
        { symbol: "SPG", name: "Simon Property" },
        { symbol: "O", name: "Realty Income" },
        { symbol: "WELL", name: "Welltower" },
        { symbol: "VICI", name: "VICI Properties" },
        { symbol: "DLR", name: "Digital Realty" },
        { symbol: "AVB", name: "AvalonBay" },
        { symbol: "EQR", name: "Equity Residential" },
        { symbol: "ARE", name: "Alexandria RE" },
        { symbol: "SBAC", name: "SBA Communications" },
        { symbol: "WY", name: "Weyerhaeuser" }
    ],
    "🇬🇧 UK (FTSE)": [
        { symbol: "SHEL", name: "Shell" },
        { symbol: "AZN", name: "AstraZeneca" },
        { symbol: "HSBA.L", name: "HSBC" },
        { symbol: "ULVR.L", name: "Unilever" },
        { symbol: "BP.L", name: "BP" },
        { symbol: "RIO.L", name: "Rio Tinto" },
        { symbol: "GSK.L", name: "GSK" },
        { symbol: "DGE.L", name: "Diageo" },
        { symbol: "BATS.L", name: "British American Tobacco" },
        { symbol: "REL.L", name: "RELX" },
        { symbol: "LLOY.L", name: "Lloyds Banking" },
        { symbol: "BARC.L", name: "Barclays" },
        { symbol: "VOD.L", name: "Vodafone" },
        { symbol: "NG.L", name: "National Grid" },
        { symbol: "RKT.L", name: "Reckitt" },
        { symbol: "PRU.L", name: "Prudential" },
        { symbol: "BA.L", name: "BAE Systems" },
        { symbol: "CPG.L", name: "Compass Group" },
        { symbol: "IAG.L", name: "IAG" },
        { symbol: "GLEN.L", name: "Glencore" }
    ],
    "🇩🇪 Germany (DAX)": [
        { symbol: "SAP", name: "SAP" },
        { symbol: "SIE.DE", name: "Siemens" },
        { symbol: "ALV.DE", name: "Allianz" },
        { symbol: "DTE.DE", name: "Deutsche Telekom" },
        { symbol: "BAS.DE", name: "BASF" },
        { symbol: "MRK.DE", name: "Merck KGaA" },
        { symbol: "VOW3.DE", name: "Volkswagen" },
        { symbol: "BMW.DE", name: "BMW" },
        { symbol: "MBG.DE", name: "Mercedes-Benz" },
        { symbol: "ADS.DE", name: "Adidas" },
        { symbol: "DBK.DE", name: "Deutsche Bank" },
        { symbol: "IFX.DE", name: "Infineon" },
        { symbol: "MUV2.DE", name: "Munich Re" },
        { symbol: "DHL.DE", name: "DHL Group" },
        { symbol: "RWE.DE", name: "RWE" },
        { symbol: "HEN3.DE", name: "Henkel" },
        { symbol: "CON.DE", name: "Continental" },
        { symbol: "BEI.DE", name: "Beiersdorf" },
        { symbol: "1COV.DE", name: "Covestro" },
        { symbol: "FRE.DE", name: "Fresenius" }
    ],
    "🇫🇷 France (CAC 40)": [
        { symbol: "MC.PA", name: "LVMH" },
        { symbol: "OR.PA", name: "L'Oréal" },
        { symbol: "RMS.PA", name: "Hermès" },
        { symbol: "TTE.PA", name: "TotalEnergies" },
        { symbol: "SAN.PA", name: "Sanofi" },
        { symbol: "AIR.PA", name: "Airbus" },
        { symbol: "SU.PA", name: "Schneider Electric" },
        { symbol: "BNP.PA", name: "BNP Paribas" },
        { symbol: "AI.PA", name: "Air Liquide" },
        { symbol: "EL.PA", name: "EssilorLuxottica" },
        { symbol: "KER.PA", name: "Kering" },
        { symbol: "CS.PA", name: "AXA" },
        { symbol: "GLE.PA", name: "Société Générale" },
        { symbol: "RI.PA", name: "Pernod Ricard" },
        { symbol: "DSY.PA", name: "Dassault Systèmes" },
        { symbol: "CAP.PA", name: "Capgemini" },
        { symbol: "VIE.PA", name: "Veolia" },
        { symbol: "DG.PA", name: "Vinci" },
        { symbol: "ORA.PA", name: "Orange" },
        { symbol: "EN.PA", name: "Engie" }
    ],
    "🇮🇹 Italy (MIB)": [
        { symbol: "ENEL.MI", name: "Enel" },
        { symbol: "ENI.MI", name: "Eni" },
        { symbol: "ISP.MI", name: "Intesa Sanpaolo" },
        { symbol: "UCG.MI", name: "UniCredit" },
        { symbol: "STLA.MI", name: "Stellantis" },
        { symbol: "RACE.MI", name: "Ferrari" },
        { symbol: "G.MI", name: "Generali" },
        { symbol: "SRG.MI", name: "Snam" },
        { symbol: "TRN.MI", name: "Terna" },
        { symbol: "TIT.MI", name: "Telecom Italia" },
        { symbol: "PRY.MI", name: "Prysmian" },
        { symbol: "STM.MI", name: "STMicroelectronics" },
        { symbol: "AMP.MI", name: "Amplifon" },
        { symbol: "BAMI.MI", name: "Banco BPM" },
        { symbol: "CPR.MI", name: "Campari" }
    ],
    "🇳🇱 Netherlands": [
        { symbol: "ASML", name: "ASML" },
        { symbol: "UNA.AS", name: "Unilever NV" },
        { symbol: "INGA.AS", name: "ING Group" },
        { symbol: "PHIA.AS", name: "Philips" },
        { symbol: "AD.AS", name: "Ahold Delhaize" },
        { symbol: "HEIA.AS", name: "Heineken" },
        { symbol: "ABN.AS", name: "ABN AMRO" },
        { symbol: "WKL.AS", name: "Wolters Kluwer" },
        { symbol: "ASM.AS", name: "ASM International" },
        { symbol: "AKZA.AS", name: "AkzoNobel" }
    ],
    "🇪🇸 Spain": [
        { symbol: "SAN.MC", name: "Banco Santander" },
        { symbol: "IBE.MC", name: "Iberdrola" },
        { symbol: "ITX.MC", name: "Inditex (Zara)" },
        { symbol: "TEF.MC", name: "Telefónica" },
        { symbol: "BBVA.MC", name: "BBVA" },
        { symbol: "REP.MC", name: "Repsol" },
        { symbol: "CABK.MC", name: "CaixaBank" },
        { symbol: "FER.MC", name: "Ferrovial" },
        { symbol: "AMS.MC", name: "Amadeus IT" },
        { symbol: "ENG.MC", name: "Enagás" }
    ],
    "🇨🇭 Switzerland": [
        { symbol: "NESN.SW", name: "Nestlé" },
        { symbol: "ROG.SW", name: "Roche" },
        { symbol: "NOVN.SW", name: "Novartis" },
        { symbol: "UBSG.SW", name: "UBS" },
        { symbol: "ZURN.SW", name: "Zurich Insurance" },
        { symbol: "ABBN.SW", name: "ABB" },
        { symbol: "CSGN.SW", name: "Credit Suisse" },
        { symbol: "SIKA.SW", name: "Sika" },
        { symbol: "GIVN.SW", name: "Givaudan" },
        { symbol: "LONN.SW", name: "Lonza" }
    ],
    "🇯🇵 Japan": [
        { symbol: "7203.T", name: "Toyota" },
        { symbol: "6758.T", name: "Sony" },
        { symbol: "6861.T", name: "Keyence" },
        { symbol: "8306.T", name: "MUFG" },
        { symbol: "9984.T", name: "SoftBank" },
        { symbol: "6501.T", name: "Hitachi" },
        { symbol: "6902.T", name: "Denso" },
        { symbol: "7751.T", name: "Canon" },
        { symbol: "8058.T", name: "Mitsubishi Corp" },
        { symbol: "9432.T", name: "NTT" },
        { symbol: "7267.T", name: "Honda" },
        { symbol: "6367.T", name: "Daikin" },
        { symbol: "8035.T", name: "Tokyo Electron" },
        { symbol: "7974.T", name: "Nintendo" },
        { symbol: "4063.T", name: "Shin-Etsu Chemical" },
        { symbol: "6954.T", name: "Fanuc" },
        { symbol: "9433.T", name: "KDDI" },
        { symbol: "4502.T", name: "Takeda" },
        { symbol: "6981.T", name: "Murata" },
        { symbol: "7741.T", name: "HOYA" }
    ],
    "🇨🇳 China / HK": [
        { symbol: "BABA", name: "Alibaba" },
        { symbol: "TCEHY", name: "Tencent" },
        { symbol: "PDD", name: "PDD (Temu)" },
        { symbol: "JD", name: "JD.com" },
        { symbol: "BIDU", name: "Baidu" },
        { symbol: "NIO", name: "NIO" },
        { symbol: "XPEV", name: "XPeng" },
        { symbol: "LI", name: "Li Auto" },
        { symbol: "0700.HK", name: "Tencent HK" },
        { symbol: "9988.HK", name: "Alibaba HK" },
        { symbol: "1299.HK", name: "AIA Group" },
        { symbol: "0939.HK", name: "CCB" },
        { symbol: "1398.HK", name: "ICBC" },
        { symbol: "0941.HK", name: "China Mobile" },
        { symbol: "2318.HK", name: "Ping An" },
        { symbol: "3690.HK", name: "Meituan" },
        { symbol: "0005.HK", name: "HSBC HK" },
        { symbol: "2628.HK", name: "China Life" },
        { symbol: "0883.HK", name: "CNOOC" },
        { symbol: "1810.HK", name: "Xiaomi" }
    ],
    "🇰🇷 Korea": [
        { symbol: "005930.KS", name: "Samsung Electronics" },
        { symbol: "000660.KS", name: "SK Hynix" },
        { symbol: "373220.KS", name: "LG Energy" },
        { symbol: "005380.KS", name: "Hyundai Motor" },
        { symbol: "051910.KS", name: "LG Chem" },
        { symbol: "006400.KS", name: "Samsung SDI" },
        { symbol: "035420.KS", name: "Naver" },
        { symbol: "035720.KS", name: "Kakao" },
        { symbol: "068270.KS", name: "Celltrion" },
        { symbol: "105560.KS", name: "KB Financial" }
    ],
    "🇹🇼 Taiwan": [
        { symbol: "TSM", name: "TSMC (ADR)" },
        { symbol: "2330.TW", name: "TSMC TW" },
        { symbol: "2317.TW", name: "Hon Hai (Foxconn)" },
        { symbol: "2454.TW", name: "MediaTek" },
        { symbol: "2412.TW", name: "Chunghwa Telecom" },
        { symbol: "2308.TW", name: "Delta Electronics" },
        { symbol: "2881.TW", name: "Fubon Financial" },
        { symbol: "2882.TW", name: "Cathay Financial" },
        { symbol: "1303.TW", name: "Nan Ya Plastics" },
        { symbol: "1301.TW", name: "Formosa Plastics" }
    ],
    "🇮🇳 India": [
        { symbol: "RELIANCE.NS", name: "Reliance Industries" },
        { symbol: "TCS.NS", name: "TCS" },
        { symbol: "HDFCBANK.NS", name: "HDFC Bank" },
        { symbol: "INFY.NS", name: "Infosys" },
        { symbol: "ICICIBANK.NS", name: "ICICI Bank" },
        { symbol: "HINDUNILVR.NS", name: "Hindustan Unilever" },
        { symbol: "SBIN.NS", name: "State Bank of India" },
        { symbol: "BHARTIARTL.NS", name: "Bharti Airtel" },
        { symbol: "ITC.NS", name: "ITC" },
        { symbol: "KOTAKBANK.NS", name: "Kotak Mahindra Bank" },
        { symbol: "LT.NS", name: "Larsen & Toubro" },
        { symbol: "AXISBANK.NS", name: "Axis Bank" },
        { symbol: "BAJFINANCE.NS", name: "Bajaj Finance" },
        { symbol: "ASIANPAINT.NS", name: "Asian Paints" },
        { symbol: "MARUTI.NS", name: "Maruti Suzuki" }
    ],
    "🇦🇺 Australia": [
        { symbol: "BHP.AX", name: "BHP Group" },
        { symbol: "CBA.AX", name: "Commonwealth Bank" },
        { symbol: "CSL.AX", name: "CSL Limited" },
        { symbol: "NAB.AX", name: "NAB" },
        { symbol: "WBC.AX", name: "Westpac" },
        { symbol: "ANZ.AX", name: "ANZ Bank" },
        { symbol: "WDS.AX", name: "Woodside Energy" },
        { symbol: "FMG.AX", name: "Fortescue" },
        { symbol: "WES.AX", name: "Wesfarmers" },
        { symbol: "TLS.AX", name: "Telstra" }
    ],
    "🇨🇦 Canada": [
        { symbol: "RY", name: "Royal Bank of Canada" },
        { symbol: "TD", name: "TD Bank" },
        { symbol: "ENB", name: "Enbridge" },
        { symbol: "CNQ", name: "Canadian Natural" },
        { symbol: "BNS", name: "Bank of Nova Scotia" },
        { symbol: "BMO", name: "Bank of Montreal" },
        { symbol: "CP", name: "Canadian Pacific" },
        { symbol: "CNI", name: "Canadian National" },
        { symbol: "SU", name: "Suncor Energy" },
        { symbol: "TRP", name: "TC Energy" }
    ],
    "🇧🇷 Brazil": [
        { symbol: "VALE", name: "Vale SA" },
        { symbol: "PBR", name: "Petrobras" },
        { symbol: "ITUB", name: "Itaú Unibanco" },
        { symbol: "BBD", name: "Bradesco" },
        { symbol: "ABEV", name: "Ambev" },
        { symbol: "BSBR", name: "Banco Santander Brasil" },
        { symbol: "SBS", name: "Companhia Saneamento" },
        { symbol: "EWZ", name: "Brazil ETF" }
    ],
    "📊 Major ETFs": [
        { symbol: "SPY", name: "S&P 500 ETF" },
        { symbol: "QQQ", name: "Nasdaq 100 ETF" },
        { symbol: "IWM", name: "Russell 2000 ETF" },
        { symbol: "DIA", name: "Dow Jones ETF" },
        { symbol: "VTI", name: "Total US Market" },
        { symbol: "VOO", name: "Vanguard S&P 500" },
        { symbol: "VEA", name: "Developed Markets" },
        { symbol: "VWO", name: "Emerging Markets" },
        { symbol: "EEM", name: "iShares Emerging" },
        { symbol: "VEU", name: "All World ex-US" },
        { symbol: "XLK", name: "Tech Select" },
        { symbol: "XLF", name: "Financial Select" },
        { symbol: "XLE", name: "Energy Select" },
        { symbol: "XLV", name: "Healthcare Select" },
        { symbol: "XLI", name: "Industrial Select" },
        { symbol: "XLY", name: "Consumer Disc Select" },
        { symbol: "XLP", name: "Consumer Staples" },
        { symbol: "XLU", name: "Utilities Select" },
        { symbol: "XLRE", name: "Real Estate Select" },
        { symbol: "XLB", name: "Materials Select" },
        { symbol: "SMH", name: "Semiconductor ETF" },
        { symbol: "ARKK", name: "ARK Innovation" },
        { symbol: "TLT", name: "20+ Year Treasury" },
        { symbol: "HYG", name: "High Yield Corporate" },
        { symbol: "LQD", name: "Investment Grade Corp" },
        { symbol: "GLD", name: "Gold ETF" },
        { symbol: "SLV", name: "Silver ETF" },
        { symbol: "USO", name: "Oil ETF" },
        { symbol: "VNQ", name: "Real Estate ETF" },
        { symbol: "KWEB", name: "China Internet ETF" }
    ],
    "🇺🇸 US Indices": [
        { symbol: "^GSPC", name: "S&P 500" },
        { symbol: "^DJI", name: "Dow Jones" },
        { symbol: "^IXIC", name: "Nasdaq" },
        { symbol: "^RUT", name: "Russell 2000" },
        { symbol: "^VIX", name: "VIX" }
    ],
    "🪙 Crypto": [
        { symbol: "BTC-USD", name: "Bitcoin" },
        { symbol: "ETH-USD", name: "Ethereum" },
        { symbol: "SOL-USD", name: "Solana" },
        { symbol: "BNB-USD", name: "Binance Coin" },
        { symbol: "XRP-USD", name: "XRP" },
        { symbol: "ADA-USD", name: "Cardano" },
        { symbol: "DOGE-USD", name: "Dogecoin" },
        { symbol: "AVAX-USD", name: "Avalanche" },
        { symbol: "DOT-USD", name: "Polkadot" },
        { symbol: "LINK-USD", name: "Chainlink" },
        { symbol: "MATIC-USD", name: "Polygon" },
        { symbol: "UNI-USD", name: "Uniswap" },
        { symbol: "ATOM-USD", name: "Cosmos" },
        { symbol: "LTC-USD", name: "Litecoin" },
        { symbol: "TRX-USD", name: "Tron" }
    ],
    "🛢️ Commodities": [
        { symbol: "GC=F", name: "Gold" },
        { symbol: "SI=F", name: "Silver" },
        { symbol: "CL=F", name: "Crude Oil WTI" },
        { symbol: "BZ=F", name: "Brent Oil" },
        { symbol: "NG=F", name: "Natural Gas" },
        { symbol: "HG=F", name: "Copper" },
        { symbol: "PL=F", name: "Platinum" },
        { symbol: "PA=F", name: "Palladium" },
        { symbol: "ZC=F", name: "Corn" },
        { symbol: "ZW=F", name: "Wheat" }
    ],
    "💱 Forex": [
        { symbol: "EURUSD=X", name: "EUR/USD" },
        { symbol: "USDJPY=X", name: "USD/JPY" },
        { symbol: "GBPUSD=X", name: "GBP/USD" },
        { symbol: "AUDUSD=X", name: "AUD/USD" },
        { symbol: "USDCAD=X", name: "USD/CAD" },
        { symbol: "USDCHF=X", name: "USD/CHF" },
        { symbol: "EURGBP=X", name: "EUR/GBP" },
        { symbol: "EURJPY=X", name: "EUR/JPY" }
    ],
    "📈 US Mid Cap A-L": [
        { symbol: "ANET", name: "Arista Networks" },
        { symbol: "ABNB", name: "Airbnb" },
        { symbol: "ADSK", name: "Autodesk" },
        { symbol: "AJG", name: "Arthur J. Gallagher" },
        { symbol: "ALGN", name: "Align Technology" },
        { symbol: "ALL", name: "Allstate" },
        { symbol: "AMAT", name: "Applied Materials" },
        { symbol: "AME", name: "Ametek" },
        { symbol: "AMPH", name: "Amphastar" },
        { symbol: "ANSS", name: "ANSYS" },
        { symbol: "APD", name: "Air Products" },
        { symbol: "APH", name: "Amphenol" },
        { symbol: "ATO", name: "Atmos Energy" },
        { symbol: "BK", name: "Bank of New York" },
        { symbol: "BKR", name: "Baker Hughes" },
        { symbol: "BR", name: "Broadridge" },
        { symbol: "CARR", name: "Carrier Global" },
        { symbol: "CBOE", name: "Cboe Global" },
        { symbol: "CDNS", name: "Cadence Design" },
        { symbol: "CE", name: "Celanese" },
        { symbol: "CEG", name: "Constellation Energy" },
        { symbol: "CHD", name: "Church & Dwight" },
        { symbol: "CHTR", name: "Charter Communications" },
        { symbol: "CLX", name: "Clorox" },
        { symbol: "CMI", name: "Cummins" },
        { symbol: "CNC", name: "Centene" },
        { symbol: "COF", name: "Capital One" },
        { symbol: "COIN", name: "Coinbase" },
        { symbol: "COR", name: "Cencora" },
        { symbol: "CPRT", name: "Copart" },
        { symbol: "CRL", name: "Charles River Labs" },
        { symbol: "DAL", name: "Delta Air Lines" },
        { symbol: "DD", name: "DuPont" },
        { symbol: "DECK", name: "Deckers Outdoor" },
        { symbol: "DKNG", name: "DraftKings" },
        { symbol: "DLTR", name: "Dollar Tree" },
        { symbol: "DOV", name: "Dover" },
        { symbol: "DOW", name: "Dow Inc" },
        { symbol: "DPZ", name: "Dominos Pizza" },
        { symbol: "DXCM", name: "DexCom" },
        { symbol: "EA", name: "Electronic Arts" },
        { symbol: "EBAY", name: "eBay" },
        { symbol: "ECL", name: "Ecolab" },
        { symbol: "EFX", name: "Equifax" },
        { symbol: "EIX", name: "Edison International" },
        { symbol: "EQT", name: "EQT Corporation" },
        { symbol: "ERIC", name: "Ericsson" },
        { symbol: "EXPD", name: "Expeditors" },
        { symbol: "EXPE", name: "Expedia" },
        { symbol: "FANG", name: "Diamondback" },
        { symbol: "FAST", name: "Fastenal" },
        { symbol: "FCX", name: "Freeport-McMoRan" },
        { symbol: "FIS", name: "Fidelity National" },
        { symbol: "FSLR", name: "First Solar" },
        { symbol: "GEN", name: "Gen Digital" },
        { symbol: "GILD", name: "Gilead Sciences" },
        { symbol: "GLW", name: "Corning" },
        { symbol: "GPN", name: "Global Payments" },
        { symbol: "GWW", name: "Grainger" },
        { symbol: "HBAN", name: "Huntington Bancshares" },
        { symbol: "HPE", name: "HP Enterprise" },
        { symbol: "HPQ", name: "HP Inc" },
        { symbol: "HRL", name: "Hormel Foods" },
        { symbol: "HUBB", name: "Hubbell" },
        { symbol: "HUM", name: "Humana" },
        { symbol: "HWM", name: "Howmet Aerospace" },
        { symbol: "IDXX", name: "IDEXX Labs" },
        { symbol: "IEX", name: "IDEX Corp" },
        { symbol: "IFF", name: "IFF" },
        { symbol: "ILMN", name: "Illumina" },
        { symbol: "IP", name: "Intl Paper" },
        { symbol: "IPG", name: "Interpublic" },
        { symbol: "IQV", name: "IQVIA" },
        { symbol: "IR", name: "Ingersoll Rand" },
        { symbol: "IRM", name: "Iron Mountain" },
        { symbol: "IT", name: "Gartner" },
        { symbol: "J", name: "Jacobs Solutions" },
        { symbol: "JBHT", name: "J.B. Hunt" },
        { symbol: "JCI", name: "Johnson Controls" },
        { symbol: "JKHY", name: "Jack Henry" },
        { symbol: "KEYS", name: "Keysight" },
        { symbol: "KMB", name: "Kimberly-Clark" },
        { symbol: "KR", name: "Kroger" },
        { symbol: "L", name: "Loews" },
        { symbol: "LDOS", name: "Leidos" },
        { symbol: "LEN", name: "Lennar" },
        { symbol: "LKQ", name: "LKQ Corp" },
        { symbol: "LNT", name: "Alliant Energy" },
        { symbol: "LUV", name: "Southwest Airlines" },
        { symbol: "LVS", name: "Las Vegas Sands" },
        { symbol: "LYB", name: "LyondellBasell" }
    ],
    "📉 US Mid Cap M-Z": [
        { symbol: "MAA", name: "Mid-America Apartment" },
        { symbol: "MAR", name: "Marriott" },
        { symbol: "MAS", name: "Masco" },
        { symbol: "MCHP", name: "Microchip Tech" },
        { symbol: "MKC", name: "McCormick" },
        { symbol: "MLM", name: "Martin Marietta" },
        { symbol: "MNST", name: "Monster Beverage" },
        { symbol: "MOH", name: "Molina Healthcare" },
        { symbol: "MPC", name: "Marathon Petroleum" },
        { symbol: "MPWR", name: "Monolithic Power" },
        { symbol: "MRO", name: "Marathon Oil" },
        { symbol: "MSCI", name: "MSCI Inc" },
        { symbol: "MTB", name: "M&T Bank" },
        { symbol: "MTD", name: "Mettler-Toledo" },
        { symbol: "NDAQ", name: "Nasdaq Inc" },
        { symbol: "NDSN", name: "Nordson" },
        { symbol: "NEM", name: "Newmont" },
        { symbol: "NTAP", name: "NetApp" },
        { symbol: "NTRS", name: "Northern Trust" },
        { symbol: "NUE", name: "Nucor" },
        { symbol: "ODFL", name: "Old Dominion" },
        { symbol: "OMC", name: "Omnicom" },
        { symbol: "ON", name: "ON Semiconductor" },
        { symbol: "OTIS", name: "Otis Worldwide" },
        { symbol: "PARA", name: "Paramount" },
        { symbol: "PAYC", name: "Paycom" },
        { symbol: "PAYX", name: "Paychex" },
        { symbol: "PCAR", name: "PACCAR" },
        { symbol: "PCG", name: "PG&E" },
        { symbol: "PEAK", name: "Healthpeak" },
        { symbol: "PKG", name: "Packaging Corp" },
        { symbol: "PODD", name: "Insulet" },
        { symbol: "POOL", name: "Pool Corp" },
        { symbol: "PPG", name: "PPG Industries" },
        { symbol: "PPL", name: "PPL Corp" },
        { symbol: "PWR", name: "Quanta Services" },
        { symbol: "PYPL", name: "PayPal" },
        { symbol: "QRVO", name: "Qorvo" },
        { symbol: "RCL", name: "Royal Caribbean" },
        { symbol: "REG", name: "Regency Centers" },
        { symbol: "RF", name: "Regions Financial" },
        { symbol: "RJF", name: "Raymond James" },
        { symbol: "RMD", name: "ResMed" },
        { symbol: "ROL", name: "Rollins" },
        { symbol: "RSG", name: "Republic Services" },
        { symbol: "SBAC", name: "SBA Communications" },
        { symbol: "SEDG", name: "SolarEdge" },
        { symbol: "SHW", name: "Sherwin-Williams" },
        { symbol: "SJM", name: "J.M. Smucker" },
        { symbol: "SNA", name: "Snap-on" },
        { symbol: "SNPS", name: "Synopsys" },
        { symbol: "SQ", name: "Block Inc" },
        { symbol: "STT", name: "State Street" },
        { symbol: "SWK", name: "Stanley Black" },
        { symbol: "SYF", name: "Synchrony" },
        { symbol: "SYY", name: "Sysco" },
        { symbol: "TAP", name: "Molson Coors" },
        { symbol: "TDG", name: "TransDigm" },
        { symbol: "TDY", name: "Teledyne" },
        { symbol: "TECH", name: "Bio-Techne" },
        { symbol: "TEL", name: "TE Connectivity" },
        { symbol: "TER", name: "Teradyne" },
        { symbol: "TRMB", name: "Trimble" },
        { symbol: "TROW", name: "T. Rowe Price" },
        { symbol: "TRV", name: "Travelers" },
        { symbol: "TSCO", name: "Tractor Supply" },
        { symbol: "TTWO", name: "Take-Two" },
        { symbol: "TYL", name: "Tyler Technologies" },
        { symbol: "UAL", name: "United Airlines" },
        { symbol: "UBER", name: "Uber" },
        { symbol: "ULTA", name: "Ulta Beauty" },
        { symbol: "URI", name: "United Rentals" },
        { symbol: "VRSN", name: "VeriSign" },
        { symbol: "VRTX", name: "Vertex Pharma" },
        { symbol: "VTR", name: "Ventas" },
        { symbol: "WAB", name: "Westinghouse Air" },
        { symbol: "WAT", name: "Waters Corp" },
        { symbol: "WDC", name: "Western Digital" },
        { symbol: "WEC", name: "WEC Energy" },
        { symbol: "WLTW", name: "Willis Towers" },
        { symbol: "WRB", name: "W.R. Berkley" },
        { symbol: "WST", name: "West Pharma" },
        { symbol: "WTW", name: "WTW PLC" },
        { symbol: "XYL", name: "Xylem" },
        { symbol: "YUM", name: "Yum! Brands" },
        { symbol: "ZBH", name: "Zimmer Biomet" },
        { symbol: "ZBRA", name: "Zebra Tech" },
        { symbol: "ZION", name: "Zions Bancorp" },
        { symbol: "ZTS", name: "Zoetis" }
    ]
};
