const TICKERS_DATA = {
    "Highlights": [
        { symbol: "SPY", name: "S&P 500 ETF" },
        { symbol: "QQQ", name: "Nasdaq 100 ETF" },
        { symbol: "NVDA", name: "NVIDIA Corp" },
        { symbol: "TSLA", name: "Tesla Inc" },
        { symbol: "AAPL", name: "Apple Inc" },
        { symbol: "MSFT", name: "Microsoft Corp" },
        { symbol: "BTC-USD", name: "Bitcoin" },
        { symbol: "ETH-USD", name: "Ethereum" },
        { symbol: "EURUSD=X", name: "EUR/USD" },
        { symbol: "GC=F", name: "Gold Futures" }
    ],
    "🇺🇸 US Indices": [
        { symbol: "^GSPC", name: "S&P 500" },
        { symbol: "^DJI", name: "Dow Jones 30" },
        { symbol: "^IXIC", name: "Nasdaq Composite" },
        { symbol: "^RUT", name: "Russell 2000" },
        { symbol: "^VIX", name: "VIX Volatility" },
        { symbol: "^NYA", name: "NYSE Composite" }
    ],
    "💻 US Tech & Growth": [
        { symbol: "AAPL", name: "Apple" },
        { symbol: "MSFT", name: "Microsoft" },
        { symbol: "NVDA", name: "NVIDIA" },
        { symbol: "GOOGL", name: "Alphabet (Google)" },
        { symbol: "AMZN", name: "Amazon" },
        { symbol: "META", name: "Meta Platforms" },
        { symbol: "TSLA", name: "Tesla" },
        { symbol: "AVGO", name: "Broadcom" },
        { symbol: "NFLX", name: "Netflix" },
        { symbol: "ADBE", name: "Adobe" },
        { symbol: "CRM", name: "Salesforce" },
        { symbol: "AMD", name: "AMD" },
        { symbol: "INTC", name: "Intel" },
        { symbol: "QCOM", name: "Qualcomm" },
        { symbol: "ORCL", name: "Oracle" },
        { symbol: "CSCO", name: "Cisco" },
        { symbol: "IBM", name: "IBM" },
        { symbol: "PLTR", name: "Palantir" },
        { symbol: "COIN", name: "Coinbase" }
    ],
    "🏦 US Blue Chips": [
        { symbol: "BRK-B", name: "Berkshire Hathaway" },
        { symbol: "JPM", name: "JPMorgan Chase" },
        { symbol: "V", name: "Visa" },
        { symbol: "MA", name: "Mastercard" },
        { symbol: "BAC", name: "Bank of America" },
        { symbol: "JNJ", name: "Johnson & Johnson" },
        { symbol: "PG", name: "Procter & Gamble" },
        { symbol: "KO", name: "Coca-Cola" },
        { symbol: "PEP", name: "PepsiCo" },
        { symbol: "MCD", name: "McDonald's" },
        { symbol: "WMT", name: "Walmart" },
        { symbol: "COST", name: "Costco" },
        { symbol: "DIS", name: "Disney" },
        { symbol: "NKE", name: "Nike" },
        { symbol: "XOM", name: "Exxon Mobil" },
        { symbol: "CVX", name: "Chevron" },
        { symbol: "PFE", name: "Pfizer" }
    ],
    "🇪🇺 Europe": [
        { symbol: "^STOXX50E", name: "Euro Stoxx 50" },
        { symbol: "ASML", name: "ASML Holding" },
        { symbol: "MC.PA", name: "LVMH (Louis Vuitton)" },
        { symbol: "OR.PA", name: "L'Oréal" },
        { symbol: "SAP", name: "SAP SE" },
        { symbol: "SIE.DE", name: "Siemens AG" },
        { symbol: "RMS.PA", name: "Hermès" },
        { symbol: "AIR.PA", name: "Airbus" },
        { symbol: "VOW3.DE", name: "Volkswagen" },
        { symbol: "DTE.DE", name: "Deutsche Telekom" },
        { symbol: "FTSEMIB.MI", name: "FTSE MIB (Index)" },
        { symbol: "ENEL.MI", name: "Enel" },
        { symbol: "ENI.MI", name: "Eni" },
        { symbol: "ISP.MI", name: "Intesa Sanpaolo" },
        { symbol: "UCG.MI", name: "UniCredit" },
        { symbol: "STLA.MI", name: "Stellantis" },
        { symbol: "FER.MI", name: "Ferrari" }
    ],
    "🌏 Asia": [
        { symbol: "^N225", name: "Nikkei 225 (Japan)" },
        { symbol: "^HSI", name: "Hang Seng (HK)" },
        { symbol: "TSM", name: "TSMC (Taiwan Semi)" },
        { symbol: "BABA", name: "Alibaba" },
        { symbol: "PDD", name: "PDD (Temu)" },
        { symbol: "TCEHY", name: "Tencent" },
        { symbol: "TM", name: "Toyota Motor" },
        { symbol: "SONY", name: "Sony Group" },
        { symbol: "005930.KS", name: "Samsung Electronics" },
        { symbol: "^BSESN", name: "BSE SENSEX (India)" }
    ],
    "🪙 Crypto": [
        { symbol: "BTC-USD", name: "Bitcoin" },
        { symbol: "ETH-USD", name: "Ethereum" },
        { symbol: "SOL-USD", name: "Solana" },
        { symbol: "BNB-USD", name: "Binance Coin" },
        { symbol: "XRP-USD", name: "XRP" },
        { symbol: "ADA-USD", name: "Cardano" },
        { symbol: "DOGE-USD", name: "Dogecoin" },
        { symbol: "AVAX-USD", name: "Avalanche" },
        { symbol: "LINK-USD", name: "Chainlink" },
        { symbol: "DOT-USD", name: "Polkadot" }
    ],
    "🛢 Commodities": [
        { symbol: "GC=F", name: "Gold" },
        { symbol: "SI=F", name: "Silver" },
        { symbol: "CL=F", name: "Crude Oil (WTI)" },
        { symbol: "BZ=F", name: "Brent Oil" },
        { symbol: "NG=F", name: "Natural Gas" },
        { symbol: "HG=F", name: "Copper" },
        { symbol: "ZC=F", name: "Corn" },
        { symbol: "ZW=F", name: "Wheat" }
    ],
    "💱 Forex": [
        { symbol: "EURUSD=X", name: "EUR/USD" },
        { symbol: "USDJPY=X", name: "USD/JPY" },
        { symbol: "GBPUSD=X", name: "GBP/USD" },
        { symbol: "AUDUSD=X", name: "AUD/USD" },
        { symbol: "USDCAD=X", name: "USD/CAD" },
        { symbol: "USDCHF=X", name: "USD/CHF" }
    ]
};
